theme: jekyll-theme-slate
name: Johanna England
markdown: kramdown

include: ["/_publications/*"]

collections:
  publications:
    output: true
    permalink: /:collection/:name
  news:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: news
    values:
      layout: news
